export const VIBE_TAGS = [
    "Just Vibing",
    "Observer Mode",
    "Here for the Read",
    "Low Energy",
    "Cooling It",
    "Listening Only",
    "Open to Talk",
    "Let’s Discuss",
    "Curious Mind",
    "Got Opinions",
    "Asking Questions",
    "Respectfully Messy",
    "Devil’s Advocate",
    "Here to Argue",
    "Pushing Back",
    "Unfiltered Thoughts",
    "Processing",
    "In My Head",
    "Feeling Chatty",
    "Quietly Healing",
    "Stirring the Pot",
    "Choosing Violence",
    "Chaos Friendly",
    "Instigating Lightly",
    "Passing Through",
    "Don’t Quote Me",
    "Here for the Comments",
    "Main Character (Today)",
    "Background Noise",
    "Logged In Late"
];
